### ISSUE TITLE
Some errors i found with helpview.nvim in the help page of :h feedkeys()

### ISSUE THREAD

**Issue by 231tr0n** [OXY2DEV/helpview.nvim#9]
Hi! I found some inconsistencies with this plugin extmarks in these areas.
The first one is in ``:h extendnew()``
![image](https://github.com/user-attachments/assets/ada3dc83-31ed-4a4b-883e-72a73812abd5)
![image](https://github.com/user-attachments/assets/0e215951-56e0-47de-ae37-119abbcd94c7)
As you can see in the above image, once I go down, the parenthesis after extend doubles becoming something from extend() to extend()().

The next one is in ``:h feedkeys()``
![image](https://github.com/user-attachments/assets/bb9269c4-6c0f-489b-91d7-f8f90127670d)
![image](https://github.com/user-attachments/assets/4ff34d2b-6503-4987-bbf8-038b4696e8b1)
As you can see in the above image, the string with some icon before changes to stringng without icon as I go down.

The third one is in ``:h nvim_feedkeys()``
![image](https://github.com/user-attachments/assets/9ead21eb-6d7d-4bb5-b98b-347e43a48af7)
![image](https://github.com/user-attachments/assets/98cb89e3-c2c4-4f4c-8cbc-21ac36e96b59)
As you can see in the above image, the nvim_feedkeys() in blue becomes nvim_feedkeys()) once i go down.

What do you think might be going wrong here.

**Comment by OXY2DEV** [comment]
Does it always happens on the exact same place?

It most likely is caused by `nvim_buf_clear_namespace()` not clearing the screen.

The last one is unfortunately not fixable due to how extmarks work. As otherwise the highlighting doesn't work with `line_hl_group`.

**Comment by 231tr0n** [comment]
> Does it always happens on the exact same place?
> 
> This is unfortunately not fixable due to how extmarks work. As otherwise the highlighting doesn't work with `line_hl_group`.

Yes it happens in the same place always.

**Comment by OXY2DEV** [comment]
Weird. I can't re-create the issue.

**Comment by 231tr0n** [comment]
> Weird. I can't re-create the issue.

Is it so ok give me a sec let me try recreating it with minimal configuration.

**Comment by 231tr0n** [comment]
> > Weird. I can't re-create the issue.
> 
> Is it so ok give me a sec let me try recreating it with minimal configuration.

Alright. Here is a minimal configuration which can reproduce the issue
```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()
require("lazy.minit").repro({
	spec = {
		"echasnovski/mini.indentscope",
		"echasnovski/mini.icons",
		"nvim-treesitter/nvim-treesitter",
		"folke/tokyonight.nvim",
		"OXY2DEV/helpview.nvim",
		"OXY2DEV/markview.nvim",
	},
})

require("mini.icons").setup({
	lsp = {
		ollama = { glyph = "", hl = "MiniIconsGreen" },
	},
})
MiniIcons.mock_nvim_web_devicons()
require("mini.indentscope").setup({
	symbol = "│",
	draw = {
		delay = 0,
		animation = require("mini.indentscope").gen_animation.none(),
	},
})

require("nvim-treesitter.configs").setup({
	ensure_installed = {
		"vim",
		"vimdoc",
	},
	sync_install = false,
	auto_install = true,
	highlight = {
		enable = true,
		additional_vim_regex_highlighting = false,
	},
})
require("helpview").setup()
require("markview").setup()
require("tokyonight").setup()
vim.cmd.colorscheme("tokyonight")
```
Hope this helps in debugging.

**Comment by OXY2DEV** [comment]
The issue is caused by `mini.indentscope`.

I can see that it only occurs when the animation is running(it doesn't go away when disabling the animation which means the animation timer is still running in the background).

I have also noticed that it doesn't matter if `helpview` was enabled or disabled as long as the indent is shown the issue exists.

Another thing to note that the issue seems to only occur when the indent is being shown so it most likely is caused by something done by `mini.indentscope`.

**Comment by 231tr0n** [comment]
> The issue is caused by `mini.indentscope`.
> 
> I can see that it only occurs when the animation is running(it doesn't go away when disabling the animation which means the animation timer is still running in the background).
> 
> I have also noticed that it doesn't matter if `helpview` was enabled or disabled as long as the indent is shown the issue exists.
> 
> Another thing to note that the issue seems to only occur when the indent is being shown so it most likely is caused by something done by `mini.indentscope`.

Cool thanks for helping me out. Will try seeing what can be done about this.

**Comment by 231tr0n** [comment]
Hi! So I found which plugin was causing the last issue. It was rainbow-delimiters.nvim.
```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()
require("lazy.minit").repro({
	spec = {
		"echasnovski/mini.indentscope",
		"echasnovski/mini.icons",
		"nvim-treesitter/nvim-treesitter",
		"HiPhish/rainbow-delimiters.nvim",
		"OXY2DEV/helpview.nvim",
	},
})

require("mini.icons").setup({
	lsp = {
		ollama = { glyph = "", hl = "MiniIconsGreen" },
	},
})
MiniIcons.mock_nvim_web_devicons()
require("mini.indentscope").setup({
	symbol = "│",
	draw = {
		delay = 0,
		animation = require("mini.indentscope").gen_animation.none(),
	},
})

require("nvim-treesitter.configs").setup({
	ensure_installed = {
		"vim",
		"vimdoc",
	},
	sync_install = false,
	auto_install = true,
	highlight = {
		enable = true,
		additional_vim_regex_highlighting = false,
	},
})
local rainbow_delimiters = require("rainbow-delimiters")
vim.g.rainbow_delimiters = {
	strategy = {
		[""] = rainbow_delimiters.strategy["global"],
		commonlisp = rainbow_delimiters.strategy["local"],
	},
	query = {
		[""] = "rainbow-delimiters",
		-- lua = "rainbow-blocks",
	},
	highlight = {
		"RainbowDelimiterRed",
		-- "RainbowDelimiterYellow",
		-- "RainbowDelimiterBlue",
		-- "RainbowDelimiterOrange",
		-- "RainbowDelimiterGreen",
		-- "RainbowDelimiterViolet",
		-- "RainbowDelimiterCyan",
	},
}
require("helpview").setup()
```

**Comment by OXY2DEV** [comment]
I am pretty sure `conceal` is responsible for this issue not any of the plugins themselves so I will have to see if `mini.nvim's` author knows anything about this issue.

**Comment by 231tr0n** [comment]
> I am pretty sure `conceal` is responsible for this issue, not any of the plugins themselves so I will have to see if `mini.nvim's` author knows anything about this issue.

Ok cool, so I am assuming rainbow-delimiters.nvim also comes under the same position as mini.indentscope is it?

**Comment by OXY2DEV** [comment]
Yeah

**Comment by echasnovski** [comment]
> I am pretty sure `conceal` is responsible for this issue, not any of the plugins themselves so I will have to see if `mini.nvim's` author knows anything about this issue.

It would have been good to mention this in echasnovski/mini.nvim#1159 **before** I had to spend time investigating which part of 'mini.indentscope' might be responsible for this. It ended up being not fun to go through avoidable debugging skill test just to construct a reproduction example without 'mini.indentscope'.

**Comment by OXY2DEV** [comment]
I would've but then it didn't make much sense why the issue happened in a completely different place then where the indent is being shown.

I also checked if the extmarks were also concealed but disabling concealing didn't fix the issue.

**Comment by 231tr0n** [comment]
> > I am pretty sure `conceal` is responsible for this issue, not any of the plugins themselves so I will have to see if `mini.nvim's` author knows anything about this issue.
> 
> It would have been good to mention this in echasnovski/mini.nvim#1159 **before** I had to spend time investigating which part of 'mini.indentscope' might be responsible for this. It ended up being not fun to go through avoidable debugging skill test just to construct a reproduction example without 'mini.indentscope'.

It is my bad i should have notified it there since i was the one who raised the issue i guess. Will make sure to do it from the next time.

**Comment by OXY2DEV** [comment]
Apparently, extmarks can remove each other.

Well, now it should be fixed.

**Comment by 231tr0n** [comment]
> Apparently, extmarks can remove each other.
> 
> Well, now it should be fixed.

All three scenarios are fixed is it. Or is it just the first two related to mini.indentscope.

**Comment by OXY2DEV** [comment]
All of them should be fixed but you can check to be sure.

**Comment by 231tr0n** [comment]
Hi @OXY2DEV . Apparently i can still see similar issues and this time, it is in ``:h helpview.nvim`` with the same old repro configuration.
![Uploading 20240822_100948.jpg …]()

![Uploading 20240822_101032.jpg …]()

**Comment by OXY2DEV** [comment]
Is it fixed now?

**Comment by 231tr0n** [comment]
> Is it fixed now?
> 
> > It doesn't seem to happen anymore on my end

It seems to be fixed now. Thank you for fixing it this fast.
